### ISSUE TITLE
Bug: Can't press button for internet connection

### ISSUE THREAD

**Issue by heubergen** [CODeRUS/sailfishos-eventsview-controls-remastered-patch#1]
When I've activate the internet connection and will then deactivate it over the eventsview, I can't press the button for it. It here and the button looking right, but I can't press it.
Its independent where I click by the button. In right this situation I can press the button for e.g. the wifi, but not for the internet access.

**Comment by CODeRUS** [comment]
What is "data"?

**Comment by heubergen** [comment]
Will update it in three minutes, sorry I had publish it to early :)

So its now update @CODeRUS

**Comment by heubergen** [comment]
Bug was away after restart my device so I will close this issue :) @CODeRUS
